version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - blog-debug
  web:
    build: .
    command: bundle exec rdbg -n --open --host 0.0.0.0 --port 12345 -c -- bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
      - "12345:12345"
    depends_on:
      - db
    networks:
      - blog-debug

volumes:
  postgres_volume:

networks:
  blog-debug:
